### ISSUE TITLE
NoClassDefFoundError in Spark-submit operation

### ISSUE THREAD

**Issue by nakhanha** [Aloja/aloja#37]
/usr/bin/spark-submit --driver-memory 5g --conf spark.sql.crossJoin.enabled=true --class io.bigdatabenchmark.v2.queries.q05.LogisticRegression /mnt/aloja/aplic2/apps/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/Resources/bigbench-ml-spark-2x.jar --fromHiveMetastore true -i bigbench_1000.q05_hive_RUN_QUERY_0_temp -o /dfs/benchmarks/bigbench/data/query_results/bigbench_1000_/q05_hive_RUN_QUERY_0_result// --type LBFGS --step-size 1 --iterations 20 --lambda 0 --numClasses 2 --convergenceTol 1e-5 --numCorrections 10 --saveClassificationResult false --saveMetaInfo true --verbose false
SPARK_MAJOR_VERSION is set to 1, using Spark
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/SparkSession
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:735)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SparkSession
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

nakhanha@hn0-hdil16:~/share/jobs_hdil16-D14v2-hive21-263/20180608_165126_ETH_HDD_bBigBench_S_D16_hdil16-D14v2-hive21-263$ spark-submit --version
SPARK_MAJOR_VERSION is set to 1, using Spark
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.6.3
      /_/

Type --help for more information.
nakhanha@hn0-hdil16:~/share/jobs_hdil16-D14v2-hive21-263/20180608_165126_ETH_HDD_bBigBench_S_D16_hdil16-D14v2-hive21-263$

Is there something I am missing ?

Thanks.

**Comment by nakhanha** [comment]
tried with both spark2-client and spark-client

nakhanha@hn0-hdil16:~/share/jobs_hdil16-D14v2-hive21-263/20180608_165126_ETH_HDD_bBigBench_S_D16_hdil16-D14v2-hive21-263$ /usr/hdp/current/spark-client/bin/spark-submit  --driver-memory 5g --conf spark.sql.crossJoin.enabled=true --class io.bigdatabenchmark.v2.queries.q05.LogisticRegression /mnt/aloja/aplic2/apps/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/Resources/bigbench-ml-spark-2x.jar --fromHiveMetastore true -i bigbench_1000.q05_hive_RUN_QUERY_0_temp -o /dfs/benchmarks/bigbench/data/query_results/bigbench_1000_/q05_hive_RUN_QUERY_0_result// --type LBFGS --step-size 1 --iterations 20 --lambda 0 --numClasses 2 --convergenceTol 1e-5 --numCorrections 10 --saveClassificationResult false --saveMetaInfo true --verbose false
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/SparkSession
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:735)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SparkSession
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more
nakhanha@hn0-hdil16:~/share/jobs_hdil16-D14v2-hive21-263/20180608_165126_ETH_HDD_bBigBench_S_D16_hdil16-D14v2-hive21-263$ /usr/hdp/current/spark2-client/bin/spark-submit  --driver-memory 5g --conf spark.sql.crossJoin.enabled=true --class io.bigdatabenchmark.v2.queries.q05.LogisticRegression /mnt/aloja/aplic2/apps/Big-Data-Benchmark-for-Big-Bench/engines/hive/queries/Resources/bigbench-ml-spark-2x.jar --fromHiveMetastore true -i bigbench_1000.q05_hive_RUN_QUERY_0_temp -o /dfs/benchmarks/bigbench/data/query_results/bigbench_1000_/q05_hive_RUN_QUERY_0_result// --type LBFGS --step-size 1 --iterations 20 --lambda 0 --numClasses 2 --convergenceTol 1e-5 --numCorrections 10 --saveClassificationResult false --saveMetaInfo true --verbose false
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/SparkSession
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:735)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.SparkSession
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more
nakhanha@hn0-hdil16:~/share/jobs_hdil16-D14v2-hive21-263/20180608_165126_ETH_HDD_bBigBench_S_D16_hdil16-D14v2-hive21-263$

**Comment by nakhanha** [comment]
Changed to Spark2 and it works
